### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by aminbabar** [samuelskim1/moodify#4]
# Sample State

- [x] State shape is flat!
- [x]  State's keys are camelCased
- [ ] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language `(```javascript...```)`. This will display the state as a code block instead of a giant line of text
    - [x]  Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka `comments` inside of `posts`
        - Some info from other tables is ok, for instance:
            - the author username and imageurl for a post. basically any info that the user can't change
            - like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by aminbabar** [comment]
- you need slices of state for joins tables that you have on the backend on the frontend too
- You do not need the UI slice of state if Spotify has no modals

**Comment by samuelskim1** [comment]
Hello Amin! I plan on using the UI slice of state to implement a modal that will render whenever a user tries to delete a playlist. The modal will confirm that the user wants to delete the playlist. This is something that spotify implements when trying to delete a playlist
